modLoader="javafml" #mandatory
loaderVersion="[41,)"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/Krxwallo/ObsidianExtension-v2/issues"

[[mods]] #mandatory
    modId="obsidian_extension" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Obsidian Extension" #mandatory
    displayURL="https://www.curseforge.com/minecraft/mc-mods/obsidian-extension"
    logoFile="icon.png"
    authors="Krxwallo"
    description="Stairs, Slabs, Walls, Doors, Buttons and Armor for (Crying) Obsidian"

[[dependencies.obsidian_extension]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.obsidian_extension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
